changelog:
  categories:
    - title: Documentation Changes 📃
      labels:
        - docs
    - title: Features 🎉
      labels:
        - feat
    - title: Bug Fixes 🐛
      labels:
        - fix
    - title: Other Changes 🤷‍♂️
      labels:
        - "*"
