name: Build & Release

on:
  push:
    branches: [canary]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      isRelease: ${{ steps.check-release.outputs.IS_RELEASE }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 25

      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off

      - name: Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Fetch git tags
        run: node ./scripts/fetch-tags.mjs ${{ github.sha }}

      - name: Check release
        id: check-release
        run: |
          if [[ $(git describe --exact-match 2> /dev/null || :) = v* ]];
            then
              echo "::set-output name=IS_RELEASE::true"
            else
              echo "::set-output name=IS_RELEASE::false"
          fi

      - name: Cache build
        uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

  release:
    if: ${{ needs.build.outputs.isRelease == 'true' }}
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off

      - name: Restore build
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - name: Publish
        run: ./scripts/publish-release.sh
